name: Robot Framework Tests

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  test:
    runs-on: windows-latest  # Use the latest Ubuntu runner

    steps:
      # Check out the repository
      - name: Checkout https://github.com/aldebaran93/atembed-py-robotFramework
        uses: actions/checkout@v3

      # Set up Python (Robot Framework requires Python)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      # Install Robot Framework and dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          #pip install -r requirements.txt
          pip install robotframework
          pip install robotframework-seriallibrary
          #pip install serial
          # Add any additional libraries you need, e.g., SeleniumLibrary
          pip install robotframework-seleniumlibrary
          pip install pyserial
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=Atemb_Keywords_Library/python_library" >> $GITHUB_ENV

      # Run Robot Framework tests
      - name: Run tests
        run: robot Atemb_Release_Suite/  # Replace with the path to your test files --pythonpath Atemb_Keywords_Library/python_library